"""Add relationships, validation, and serialization rules

Revision ID: 054071666b36
Revises: 14262f111a11
Create Date: 2024-02-03 11:41:47.763441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054071666b36'
down_revision = '14262f111a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('need',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('need',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
